config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  devise_for :users

  post 'complete/:task', controller: 'tasks', action: :complete, as: 'complete'
  delete 'uncomplete/:task', controller: 'tasks', action: :uncomplete, as: 'uncomplete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/progress.rb
class Progress < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :progress
  has_many :users, through: :progress
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :progress
  has_many :tasks, through: :progress

  def has_task?(task)
    self.tasks.each do |t|
      return true if t ==task
    end
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    @tasks = Task.all
  end

  def complete
    complete = Progress.new
    complete.user = current_user
    complete.task_id = params[:task]
    complete.save
    redirect_to root_path
  end

  def uncomplete
    progress = Progress.find_by( {task: params[:task], user: current_user })
    progress.destroy
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def get_qty
    current_user.progress.count
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba2Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      #content{ margin-top: 100px }
    </style>
  </head>

  <body>
    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
      <div class="container">
        <a href="<%= root_path %>" class="navbar-brand">Prueba rails</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <small style="color: lightgrey">Completados: <%= get_qty %>/9</small>
        <div><%= link_to 'logout', destroy_user_session_path, method: :delete %></div>
      </div>
    </div>
    <div class="container" id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <% @tasks.each_slice(3) do |row| %>
      <% row.each do |task| %>
        <div class="col task">
          <%= image_tag task.picture , class: 'img-fluid' %>
          <h4><%= task.title %></h4>
          <br>
          <% unless current_user.has_task?(task) %>
          <%= link_to 'Listo', complete_path(task: task), method: :post, class: 'btn btn-primary' %>
          <% else %>
          <%= link_to 'NO Listo', uncomplete_path(task: task), method: :delete, class: 'btn btn-danger' %>
          <% end %>
        </div>
    <% end %>
    <div class="w-100"></div>
  <% end %>
  </div>
</div>

<style media="screen">
 img{
   max-height: 200px
 }
 .col.task{
   border: 1px solid lightblue;
   margin-bottom:2em;
   text-align:center;
   padding: 0.8em 0
 }
</style>